#!/usr/bin/env bash
# Bash script that will display information about subdomains
my_subdomains(){
    result=$(dig "$1.$2" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -1 | tr '\n' ' ')
    echo "$1 $result" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" == 1 ]
then
    my_subdomains "www" "$1"
    my_subdomains "lb-01" "$1"
    my_subdomains "web-01" "$1"
    my_subdomains "web-02" "$1"
elif [ "$#" == 2 ]
then
    my_subdomains "$1" "$2"
fi
