#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ $i -lt 9 ]
    do
        echo "Holberton School"
        if [ $i -eq 3 ]
        then 
            echo "bad luck"
        elif [ $i -eq 6 ]
        then
            echo "good luck"
        fi
        ((i++))
done
    