#!/usr/bin/env bash
# This script displays the time

hour=0
while [ $hour -lt 12 ]; do
    echo "Hour: $hour"
    min=1
    while [ $min -lt 60 ]; do
        echo "$min"
        ((min++))
    done
    ((hour++))
done